---
image: alpine/edge
environment:
  RUSTUP_OVERRIDE_BUILD_TRIPLE: x86_64-unknown-linux-musl
  CARGO_HUSKEY_DONT_INSTALL_HOOKS: true
packages:
  - rustup
  - redis
sources:
  - https://git.sr.ht/~grauwoelfchen/fourche
tasks:
  - setup: |
      rustup-init -y \
        --default-host $RUSTUP_OVERRIDE_BUILD_TRIPLE \
        --default-toolchain stable
      source ~/.cargo/env
      rustup set profile minimal
      rustup component add clippy rustfmt
      rustup --version
      rustc --version
      cargo --version
  - check: |
      source ~/.cargo/env
      cd fourche
      make vet-check
  - format: |
      source ~/.cargo/env
      cd fourche
      make vet-format
  - lint: |
      source ~/.cargo/env
      cd fourche
      make vet-lint
  # NOTE: no integration test
  - test: |
      source ~/.cargo/env
      cd fourche
      make test-unit
  - build: |
      source ~/.cargo/env
      cd fourche
      make build
